--
-- Person table
--
CREATE TABLE public.person (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address character varying(100) NOT NULL,
    first_name character varying(80) NOT NULL,
    gender character varying(10) NOT NULL,
    last_name character varying(80) NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);
